#baseurl = "/"
baseurl = "https://xiexinyls.github.io/xxsite/"
languageCode = "en-us"
title = "Xin Xie's Personal Website"
theme = "hugo-xx"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
publishDir = "docs"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
[[menu.main]]
    name = "Data Science"
    url = "/datasci/"
    weight = 2

[params]
    description = "Xin's Personal Website."
    footer = "&copy; Xin Xie 2020 | [LinkedIn](https://www.linkedin.com/in/xin-xie-ph-d-1274595a/)"
